import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useUserContext } from '../context/user'

export default function Home() {

  // Getting user object using useUserContext Hook
  const { user } = useUserContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Context API Tutorial</h1>

        <p>Logged in User: <strong>{user.name}</strong></p>
        <p>User token: <strong>{user.token}</strong></p>

      </main>
    </div>
  )
}
